CREATE TABLE Users (
    UID SERIAL PRIMARY KEY NOT NULL,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(250) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL
);

CREATE TABLE Transactions (
    TID SERIAL PRIMARY KEY NOT NULL,
    UID INT NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    -- date DATE NOT NULL,
    description VARCHAR(250),
    FOREIGN KEY (UID) REFERENCES Users(UID)
);